### ISSUE TITLE
Load many locations

### ISSUE THREAD

**Issue by kamov** [SaulBurgos/easyLocator#3]
Hi,
How you handle many locations on the map?
It's possible to load locations only of map active, and when user drag map, then locations is re-populate?
Thanks

**Comment by SaulBurgos** [comment]
the plugin has a option called "useMarkerCluster" if is true, the plugin will use this library: 

https://github.com/googlemaps/js-marker-clusterer

is a client library to handle with lots of markers on map.  the library does a great job. here and example

https://googlemaps.github.io/js-marker-clusterer/examples/speed_test_example.html

**Comment by kamov** [comment]
Thanks for your reply.
Yes I know about cluster.
But as I know also cluster mode load all locations.

I see certain other sites which display a map with a lot of locations (10k or 100k or even more).
They just display locations of active map, and when user drag, they re-populate map with new locations.

**Comment by SaulBurgos** [comment]
aaah yes, that is server side cluster. the plugin does not work in that way only client cluster.

This article  explain everything with php just convert it to the language that you are using...

https://appelsiini.net/2008/introduction-to-marker-clustering-with-google-maps/

or you can buy the solution 

https://codecanyon.net/item/google-map-server-side-markers-clustering-v21/8998709

**Comment by kamov** [comment]
WOW, thanks a lot! I was searching for this, but really I can't find anything also in google docs.
